'use client';

import { useState } from 'react';

export default function Home() {
  const [themeName, setThemeName] = useState('Readdy Theme');
  const [themeDescription, setThemeDescription] = useState('Generated by Readdy.ai');
  const [manifestFile, setManifestFile] = useState<File | null>(null);
  const [assetFiles, setAssetFiles] = useState<File[]>([]);
  const [converting, setConverting] = useState(false);
  const [error, setError] = useState<string | null>(null);

  const handleAssetsFolderUpload = (e: React.ChangeEvent<HTMLInputElement>) => {
    const files = Array.from(e.target.files || []);

    // manifest.jsonとassetsフォルダのファイルを分離
    const manifest = files.find(f => f.name === 'manifest.json' || f.webkitRelativePath.endsWith('manifest.json'));
    const assets = files.filter(f =>
      f.webkitRelativePath.includes('/assets/') ||
      f.webkitRelativePath.includes('/dist/assets/')
    );

    if (manifest) {
      setManifestFile(manifest);
    }
    if (assets.length > 0) {
      setAssetFiles(assets);
    }

    setError(null);
  };

  const handleZipUpload = async (e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0];
    if (!file) return;

    // ZIPファイルをそのまま保存（サーバー側で解凍）
    setManifestFile(file);
    setAssetFiles([]);
    setError(null);
  };

  const handleConvert = async () => {
    if (!manifestFile) {
      setError('manifest.jsonをアップロードしてください');
      return;
    }

    setConverting(true);
    setError(null);

    try {
      const formData = new FormData();
      formData.append('manifest', manifestFile);
      formData.append('themeName', themeName);
      formData.append('themeDescription', themeDescription);

      // assetsフォルダのファイルを追加
      assetFiles.forEach(file => {
        // webkitRelativePathから実際のファイル名を取得
        const fileName = file.webkitRelativePath.split('/assets/')[1] || file.name;
        formData.append('assets', new File([file], fileName, { type: file.type }));
      });

      const response = await fetch('/api/convert', {
        method: 'POST',
        body: formData,
      });

      if (!response.ok) {
        const errorData = await response.json();
        throw new Error(errorData.error || '変換に失敗しました');
      }

      // ZIPファイルをダウンロード
      const blob = await response.blob();
      const url = window.URL.createObjectURL(blob);
      const a = document.createElement('a');
      a.href = url;
      a.download = `${themeName.toLowerCase().replace(/\s+/g, '-')}.zip`;
      document.body.appendChild(a);
      a.click();
      window.URL.revokeObjectURL(url);
      document.body.removeChild(a);

    } catch (err: any) {
      setError(err.message || '変換中にエラーが発生しました');
    } finally {
      setConverting(false);
    }
  };

  return (
    <div className="min-h-screen bg-gradient-to-br from-purple-50 to-blue-50 py-12 px-4">
      <div className="max-w-3xl mx-auto">
        <div className="bg-white rounded-2xl shadow-xl p-8">
          <div className="mb-8 text-center">
            <h1 className="text-4xl font-bold text-gray-900 mb-2">
              Readdy.ai → WordPress
            </h1>
            <p className="text-gray-600">
              Viteテーマを WordPress テーマに変換
            </p>
          </div>

          <div className="space-y-6">
            {/* Theme Name */}
            <div>
              <label className="block text-sm font-medium text-gray-700 mb-2">
                テーマ名
              </label>
              <input
                type="text"
                value={themeName}
                onChange={(e) => setThemeName(e.target.value)}
                className="w-full px-4 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-purple-500 focus:border-transparent"
                placeholder="例: My Awesome Theme"
              />
            </div>

            {/* Theme Description */}
            <div>
              <label className="block text-sm font-medium text-gray-700 mb-2">
                テーマ説明
              </label>
              <textarea
                value={themeDescription}
                onChange={(e) => setThemeDescription(e.target.value)}
                rows={3}
                className="w-full px-4 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-purple-500 focus:border-transparent"
                placeholder="例: A beautiful theme generated by Readdy.ai"
              />
            </div>

            {/* File Upload */}
            <div>
              <label className="block text-sm font-medium text-gray-700 mb-2">
                Viteビルド結果
              </label>

              {/* Tab Selection */}
              <div className="flex gap-4 mb-4">
                <button
                  type="button"
                  onClick={() => setError(null)}
                  className="text-sm font-medium text-purple-600 border-b-2 border-purple-600 pb-1"
                >
                  フォルダ
                </button>
                <button
                  type="button"
                  onClick={() => setError(null)}
                  className="text-sm font-medium text-gray-500 pb-1"
                >
                  ZIP
                </button>
              </div>

              <div className="border-2 border-dashed border-gray-300 rounded-lg p-8 text-center hover:border-purple-500 transition-colors">
                {/* Folder Upload */}
                <input
                  type="file"
                  // @ts-ignore
                  webkitdirectory=""
                  directory=""
                  multiple
                  onChange={handleAssetsFolderUpload}
                  className="hidden"
                  id="folder-upload"
                />
                {/* ZIP Upload */}
                <input
                  type="file"
                  accept=".zip"
                  onChange={handleZipUpload}
                  className="hidden"
                  id="zip-upload"
                />
                <label
                  htmlFor="folder-upload"
                  className="cursor-pointer"
                >
                  <svg
                    className="mx-auto h-12 w-12 text-gray-400 mb-4"
                    stroke="currentColor"
                    fill="none"
                    viewBox="0 0 48 48"
                    aria-hidden="true"
                  >
                    <path
                      d="M28 8H12a4 4 0 00-4 4v20m32-12v8m0 0v8a4 4 0 01-4 4H12a4 4 0 01-4-4v-4m32-4l-3.172-3.172a4 4 0 00-5.656 0L28 28M8 32l9.172-9.172a4 4 0 015.656 0L28 28m0 0l4 4m4-24h8m-4-4v8m-12 4h.02"
                      strokeWidth={2}
                      strokeLinecap="round"
                      strokeLinejoin="round"
                    />
                  </svg>
                  <p className="text-sm text-gray-600">
                    <span className="font-semibold text-purple-600">
                      クリックしてフォルダまたはZIPを選択
                    </span>
                  </p>
                  <p className="text-xs text-gray-500 mt-2">
                    manifest.json と assets フォルダを含むディレクトリ、またはZIPファイル
                  </p>
                </label>
                <label
                  htmlFor="zip-upload"
                  className="mt-3 inline-block text-sm text-purple-600 hover:text-purple-700 cursor-pointer"
                >
                  または ZIPファイルを選択
                </label>
              </div>

              {/* File Status */}
              {manifestFile && (
                <div className="mt-4 space-y-2">
                  <div className="flex items-center text-sm text-green-600">
                    <svg className="w-5 h-5 mr-2" fill="currentColor" viewBox="0 0 20 20">
                      <path fillRule="evenodd" d="M10 18a8 8 0 100-16 8 8 0 000 16zm3.707-9.293a1 1 0 00-1.414-1.414L9 10.586 7.707 9.293a1 1 0 00-1.414 1.414l2 2a1 1 0 001.414 0l4-4z" clipRule="evenodd" />
                    </svg>
                    manifest.json 検出
                  </div>
                  {assetFiles.length > 0 && (
                    <div className="flex items-center text-sm text-green-600">
                      <svg className="w-5 h-5 mr-2" fill="currentColor" viewBox="0 0 20 20">
                        <path fillRule="evenodd" d="M10 18a8 8 0 100-16 8 8 0 000 16zm3.707-9.293a1 1 0 00-1.414-1.414L9 10.586 7.707 9.293a1 1 0 00-1.414 1.414l2 2a1 1 0 001.414 0l4-4z" clipRule="evenodd" />
                      </svg>
                      {assetFiles.length} 個のアセットファイル検出
                    </div>
                  )}
                </div>
              )}
            </div>

            {/* Error Message */}
            {error && (
              <div className="bg-red-50 border border-red-200 rounded-lg p-4">
                <p className="text-sm text-red-600">{error}</p>
              </div>
            )}

            {/* Convert Button */}
            <button
              onClick={handleConvert}
              disabled={!manifestFile || converting}
              className="w-full bg-purple-600 text-white py-3 px-6 rounded-lg font-semibold hover:bg-purple-700 disabled:bg-gray-300 disabled:cursor-not-allowed transition-colors"
            >
              {converting ? '変換中...' : 'WordPressテーマに変換'}
            </button>
          </div>

          {/* Instructions */}
          <div className="mt-8 p-6 bg-gray-50 rounded-lg">
            <h3 className="font-semibold text-gray-900 mb-3">使い方</h3>
            <ol className="list-decimal list-inside space-y-2 text-sm text-gray-600">
              <li>Readdy.aiでViteプロジェクトをビルド（<code className="bg-gray-200 px-1 rounded">npm run build</code>）</li>
              <li>ビルド結果のディレクトリ全体をアップロード（distフォルダなど）</li>
              <li>テーマ名と説明を入力</li>
              <li>「WordPressテーマに変換」をクリック</li>
              <li>ダウンロードされたZIPをWordPressの「テーマ」→「新規追加」からアップロード</li>
            </ol>
          </div>
        </div>
      </div>
    </div>
  );
}