#!/bin/bash
set -e

# WordPressの初期化が完了するまで待機
while [ ! -f /var/www/html/wp-config.php ]; do
  echo "Waiting for WordPress to be initialized..."
  sleep 2
done

echo "WordPress initialized. Setting up URLs..."

# 環境変数からURLを取得
WP_HOME_URL="${WP_HOME:-https://trust-code.net}"
WP_SITEURL_URL="${WP_SITEURL:-https://trust-code.net}"

# wp-config.php に URL 設定を追加（最優先）
if [ -f /var/www/html/wp-config.php ]; then
  echo "Configuring wp-config.php with URL settings..."

  # 既存の URL 設定セクションを削除（重複を避ける）
  sed -i '/=== URL Settings.*Auto-generated/,/=== End of Auto-generated Settings ===/d' /var/www/html/wp-config.php

  # "That's all, stop editing!" の前に挿入
  sed -i "/\/\* That's all, stop editing/i\\
// === URL Settings (Auto-generated by init-wordpress.sh) ===\\
define('WP_HOME', '$WP_HOME_URL');\\
define('WP_SITEURL', '$WP_SITEURL_URL');\\
\\
// Force HTTPS for admin (if using HTTPS)\\
if (strpos('$WP_HOME_URL', 'https://') === 0) {\\
  define('FORCE_SSL_ADMIN', true);\\
  // Set server variables for proper HTTPS detection\\
  if (!empty(\\\$_SERVER['HTTP_X_FORWARDED_PROTO']) && \\\$_SERVER['HTTP_X_FORWARDED_PROTO'] === 'https') {\\
    \\\$_SERVER['HTTPS'] = 'on';\\
    \\\$_SERVER['SERVER_PORT'] = 443;\\
  }\\
}\\
// === End of Auto-generated Settings ===\\
\\
" /var/www/html/wp-config.php

  echo "wp-config.php configured with URL: $WP_HOME_URL"
fi

# wp-cliを使用してデータベースのURLを更新（フォールバック）
if command -v wp &> /dev/null; then
  echo "Updating WordPress URLs in database..."
  wp option update home "$WP_HOME_URL" --allow-root --path=/var/www/html || echo "Failed to update home URL"
  wp option update siteurl "$WP_SITEURL_URL" --allow-root --path=/var/www/html || echo "Failed to update siteurl URL"
  echo "WordPress URLs updated to: $WP_HOME_URL"

  echo "Setting up permalink structure for React Router..."
  # パーマリンク構造を設定（React Routerのルーティングに必要）
  wp rewrite structure '/%postname%/' --allow-root --path=/var/www/html || echo "Failed to set permalink structure"
  # .htaccess を強制生成
  wp rewrite flush --hard --allow-root --path=/var/www/html || echo "Failed to flush rewrite rules"
  echo "Permalink structure configured"
else
  echo "wp-cli not found, skipping database URL update"
fi

# .htaccess を強制作成（React SPAルーティング用）
# wp rewrite flush が正しく動作しない場合があるため、常に確実なルールを設定
if [ ! -f /var/www/html/.htaccess ] || ! grep -q "RewriteRule" /var/www/html/.htaccess; then
  echo "Creating .htaccess for React SPA routing..."
  cat > /var/www/html/.htaccess << 'HTACCESS_EOF'
# BEGIN WordPress
<IfModule mod_rewrite.c>
RewriteEngine On
RewriteRule .* - [E=HTTP_AUTHORIZATION:%{HTTP:Authorization}]
RewriteBase /
RewriteRule ^index\.php$ - [L]
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d
RewriteRule . /index.php [L]
</IfModule>
# END WordPress
HTACCESS_EOF
  echo ".htaccess created successfully"
else
  echo ".htaccess already exists with RewriteRule"
fi

echo "WordPress initialization complete."