import { NextRequest, NextResponse } from 'next/server';
import archiver from 'archiver';
import AdmZip from 'adm-zip';

export async function POST(request: NextRequest) {
  try {
    const formData = await request.formData();

    // フォームデータから取得
    const manifestFile = formData.get('manifest') as File;
    const assetFiles = formData.getAll('assets') as File[];
    const themeName = formData.get('themeName') as string || 'Readdy Theme';
    const themeDescription = formData.get('themeDescription') as string || 'Generated by Readdy.ai';
    const themeSlug = themeName.toLowerCase().replace(/\s+/g, '-');

    if (!manifestFile) {
      return NextResponse.json({ error: 'manifest.json is required' }, { status: 400 });
    }

    let manifestText: string;
    let extractedAssets: { name: string; buffer: Buffer }[] = [];

    // ZIPファイルかどうか判定
    if (manifestFile.name.endsWith('.zip')) {
      // ZIPファイルを解凍
      const zipBuffer = Buffer.from(await manifestFile.arrayBuffer());
      const zip = new AdmZip(zipBuffer);
      const zipEntries = zip.getEntries();

      // デバッグ: ZIP内のファイル一覧をログ出力
      console.log('ZIP contents:');
      zipEntries.forEach(entry => {
        console.log(' -', entry.entryName, entry.isDirectory ? '[DIR]' : '');
      });

      // manifest.jsonを探す（.vite/manifest.json、dist/.vite/manifest.json、out/.vite/manifest.jsonなど）
      const manifestEntry = zipEntries.find(entry =>
        entry.entryName.includes('manifest.json') && !entry.isDirectory
      );

      if (!manifestEntry) {
        console.error('Available files:', zipEntries.map(e => e.entryName).join(', '));

        // ビルド結果がないか確認
        const hasSourceFiles = zipEntries.some(e => e.entryName.includes('package.json') || e.entryName.includes('src/'));
        const errorMsg = hasSourceFiles
          ? 'このZIPにはソースコードが含まれています。まず "npm run build" を実行してから、ビルド結果のフォルダ（dist/ または out/）をZIPにしてください。'
          : 'manifest.json not found in ZIP. Files found: ' + zipEntries.map(e => e.entryName).slice(0, 10).join(', ');

        return NextResponse.json({ error: errorMsg }, { status: 400 });
      }

      console.log('Found manifest at:', manifestEntry.entryName);
      manifestText = manifestEntry.getData().toString('utf8');

      // assetsフォルダのファイルを抽出
      for (const entry of zipEntries) {
        if (entry.isDirectory) continue;

        // assets/ または dist/assets/ 配下のファイルのみ
        const entryPath = entry.entryName;
        if (entryPath.includes('/assets/')) {
          // ファイル名を抽出（パスの最後の部分）
          const parts = entryPath.split('/assets/');
          const fileName = parts[parts.length - 1];

          if (fileName && !fileName.includes('/')) {
            console.log('Adding asset:', fileName);
            extractedAssets.push({
              name: fileName,
              buffer: entry.getData()
            });
          }
        }
      }
    } else {
      // 通常のmanifest.jsonファイル
      manifestText = await manifestFile.text();

      // assetsファイルをバッファに変換
      for (const file of assetFiles) {
        extractedAssets.push({
          name: file.name,
          buffer: Buffer.from(await file.arrayBuffer())
        });
      }
    }

    const manifest = JSON.parse(manifestText);

    // WordPress theme files を生成
    const styleCSS = generateStyleCSS(themeName, themeDescription);
    const functionsPHP = generateFunctionsPHP();
    const indexPHP = generateIndexPHP();

    // ZIP生成
    const archive = archiver('zip', { zlib: { level: 9 } });
    const chunks: Buffer[] = [];

    archive.on('data', (chunk: Buffer) => chunks.push(chunk));
    archive.on('end', () => {});
    archive.on('error', (err: Error) => {
      throw err;
    });

    // ファイルをZIPに追加
    archive.append(styleCSS, { name: `${themeSlug}/style.css` });
    archive.append(functionsPHP, { name: `${themeSlug}/functions.php` });
    archive.append(indexPHP, { name: `${themeSlug}/index.php` });
    archive.append(manifestText, { name: `${themeSlug}/manifest.json` });

    // assetsフォルダのファイルを追加
    for (const asset of extractedAssets) {
      archive.append(asset.buffer, { name: `${themeSlug}/assets/${asset.name}` });
    }

    // スクリーンショット（デフォルト画像）
    const screenshot = generateDefaultScreenshot();
    archive.append(screenshot, { name: `${themeSlug}/screenshot.png` });

    // ZIP完成
    archive.finalize();

    // chunksを結合
    await new Promise((resolve) => {
      archive.on('end', resolve);
    });

    const zipBuffer = Buffer.concat(chunks);

    // レスポンス返却
    return new NextResponse(zipBuffer, {
      headers: {
        'Content-Type': 'application/zip',
        'Content-Disposition': `attachment; filename="${themeSlug}.zip"`,
      },
    });

  } catch (error) {
    console.error('Conversion error:', error);
    return NextResponse.json(
      { error: 'Failed to convert theme' },
      { status: 500 }
    );
  }
}

function generateStyleCSS(themeName: string, description: string): string {
  return `/*
Theme Name: ${themeName}
Description: ${description}
Version: 1.0.0
Author: Readdy.ai
Author URI: https://readdy.ai
License: MIT
*/
`;
}

function generateFunctionsPHP(): string {
  return `<?php
/**
 * ${new Date().getFullYear()} Readdy.ai WordPress Theme
 * Auto-generated theme functions
 */

/* ========== テーマサポートの設定 ========== */
function readdy_theme_setup() {
  add_theme_support('title-tag');
  add_theme_support('html5', array(
    'search-form',
    'comment-form',
    'comment-list',
    'gallery',
    'caption',
  ));
  add_theme_support('post-thumbnails');
}
add_action('after_setup_theme', 'readdy_theme_setup');

/* ========== WordPressデフォルトスタイルを無効化 ========== */
function readdy_remove_wp_styles() {
  wp_dequeue_style('wp-block-library');
  wp_dequeue_style('wp-block-library-theme');
  wp_dequeue_style('classic-theme-styles');
  wp_dequeue_style('global-styles');
}
add_action('wp_enqueue_scripts', 'readdy_remove_wp_styles', 100);

/* ========== Vite資産の読み込み ========== */
function readdy_theme_assets() {
  $dir  = get_template_directory();
  $uri  = get_template_directory_uri();
  $mf   = $dir . '/manifest.json';

  if (!file_exists($mf)) {
    error_log('Readdy Theme: manifest.json not found at ' . $mf);
    return;
  }

  $manifest = json_decode(file_get_contents($mf), true);
  $entry = null;
  foreach ($manifest as $k => $v) {
    if (!empty($v['isEntry'])) {
      $entry = $v;
      break;
    }
  }

  if (!$entry) {
    error_log('Readdy Theme: No entry found in manifest.json');
    return;
  }

  // CSS
  if (!empty($entry['css'])) {
    foreach ($entry['css'] as $css) {
      $css_url = $uri . '/' . $css;
      wp_enqueue_style('readdy-'.md5($css), $css_url, [], null);
    }
  }

  // JS（type=module を付与）
  $js_url = $uri . '/' . $entry['file'];
  wp_enqueue_script('readdy-main', $js_url, [], null, true);
  wp_script_add_data('readdy-main', 'type', 'module');
}
add_action('wp_enqueue_scripts', 'readdy_theme_assets');
`;
}

function generateIndexPHP(): string {
  return `<!DOCTYPE html>
<html <?php language_attributes(); ?>>
<head>
  <meta charset="<?php bloginfo('charset'); ?>">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <?php wp_head(); ?>
</head>
<body <?php body_class(); ?>>
  <div id="root"></div>
  <?php wp_footer(); ?>
</body>
</html>
`;
}

function generateDefaultScreenshot(): Buffer {
  // 1200x900の透明PNG（最小限のバイト）
  // 実際の実装では、SVGから生成したり、デフォルト画像を用意する
  const base64PNG = 'iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mNk+M9QDwADhgGAWjR9awAAAABJRU5ErkJggg==';
  return Buffer.from(base64PNG, 'base64');
}